# Generated by Django 5.2.3 on 2025-06-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionachievements',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
