# Generated by Django 4.2.19 on 2025-06-26 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_feedback"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="text",
            new_name="content",
        ),
    ]
