# Generated by Django 5.2.3 on 2025-06-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_useractionachievements_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Main_screen',
            field=models.CharField(default='daily', max_length=10),
        ),
    ]
