# Generated by Django 4.2.19 on 2025-03-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_allcombos5_dish_inorganicinfo_inorganicvalue_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NPs",
            new_name="NP",
        ),
        migrations.RenameModel(
            old_name="NPItems",
            new_name="NPItem",
        ),
        migrations.AddField(
            model_name="proximate",
            name="Carbohydrate",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="proximate",
            name="Energy",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="proximate",
            name="Fat",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="proximate",
            name="Fibre",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="proximate",
            name="Protein",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
