# Generated by Django 4.2.19 on 2025-03-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_rename_nps_np_rename_npitems_npitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inorganic",
            fields=[
                (
                    "Food_Code",
                    models.CharField(
                        default="zero", max_length=7, primary_key=True, serialize=False
                    ),
                ),
                ("Food_Name", models.CharField(max_length=100)),
                ("Description", models.CharField(max_length=500)),
                ("Group", models.CharField(max_length=3)),
                ("Protein", models.FloatField(blank=True, max_length=255, null=True)),
                ("Fat", models.FloatField(blank=True, max_length=255, null=True)),
                (
                    "Carbohydrate",
                    models.FloatField(blank=True, max_length=255, null=True),
                ),
                ("Energy", models.FloatField(blank=True, max_length=255, null=True)),
                ("Fibre", models.FloatField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vitamin",
            fields=[
                (
                    "Food_Code",
                    models.CharField(
                        default="zero", max_length=7, primary_key=True, serialize=False
                    ),
                ),
                ("Food_Name", models.CharField(max_length=100)),
                ("Description", models.CharField(max_length=500)),
                ("Group", models.CharField(max_length=3)),
                ("Protein", models.FloatField(blank=True, max_length=255, null=True)),
                ("Fat", models.FloatField(blank=True, max_length=255, null=True)),
                (
                    "Carbohydrate",
                    models.FloatField(blank=True, max_length=255, null=True),
                ),
                ("Energy", models.FloatField(blank=True, max_length=255, null=True)),
                ("Fibre", models.FloatField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="inorganicvalue",
            name="Food",
        ),
        migrations.RemoveField(
            model_name="inorganicvalue",
            name="Inorganic",
        ),
        migrations.DeleteModel(
            name="ListOfTable",
        ),
        migrations.DeleteModel(
            name="Note",
        ),
        migrations.RemoveField(
            model_name="proximatevalue",
            name="Food",
        ),
        migrations.RemoveField(
            model_name="proximatevalue",
            name="Nutrient",
        ),
        migrations.RemoveField(
            model_name="vitaminvalue",
            name="Food",
        ),
        migrations.RemoveField(
            model_name="vitaminvalue",
            name="Vitamin",
        ),
        migrations.AlterField(
            model_name="proximate",
            name="Carbohydrate",
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="proximate",
            name="Energy",
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="proximate",
            name="Fat",
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="proximate",
            name="Fibre",
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="proximate",
            name="Protein",
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="InorganicInfo",
        ),
        migrations.DeleteModel(
            name="InorganicValue",
        ),
        migrations.DeleteModel(
            name="ProximateInfo",
        ),
        migrations.DeleteModel(
            name="ProximateValue",
        ),
        migrations.DeleteModel(
            name="VitaminInfo",
        ),
        migrations.DeleteModel(
            name="VitaminValue",
        ),
    ]
