# Generated by Django 4.2.19 on 2025-03-04 12:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_inorganic_vitamin_remove_inorganicvalue_food_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inorganic",
            old_name="Carbohydrate",
            new_name="Calcium",
        ),
        migrations.RenameField(
            model_name="inorganic",
            old_name="Energy",
            new_name="Iron",
        ),
        migrations.RenameField(
            model_name="vitamin",
            old_name="Carbohydrate",
            new_name="Folate",
        ),
        migrations.RemoveField(
            model_name="inorganic",
            name="Description",
        ),
        migrations.RemoveField(
            model_name="inorganic",
            name="Fat",
        ),
        migrations.RemoveField(
            model_name="inorganic",
            name="Fibre",
        ),
        migrations.RemoveField(
            model_name="inorganic",
            name="Food_Name",
        ),
        migrations.RemoveField(
            model_name="inorganic",
            name="Group",
        ),
        migrations.RemoveField(
            model_name="inorganic",
            name="Protein",
        ),
        migrations.RemoveField(
            model_name="vitamin",
            name="Description",
        ),
        migrations.RemoveField(
            model_name="vitamin",
            name="Energy",
        ),
        migrations.RemoveField(
            model_name="vitamin",
            name="Fat",
        ),
        migrations.RemoveField(
            model_name="vitamin",
            name="Fibre",
        ),
        migrations.RemoveField(
            model_name="vitamin",
            name="Food_Name",
        ),
        migrations.RemoveField(
            model_name="vitamin",
            name="Group",
        ),
        migrations.RemoveField(
            model_name="vitamin",
            name="Protein",
        ),
    ]
