# Generated by Django 4.2.19 on 2025-03-06 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_remove_dish_a_remove_dish_aa_remove_dish_ab_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dish",
            old_name="Food_Group",
            new_name="Food_Groups",
        ),
        migrations.RenameField(
            model_name="dish",
            old_name="Quantity",
            new_name="Quantities",
        ),
    ]
