# Generated by Django 4.2.19 on 2025-03-06 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_rename_food_group_dish_food_groups_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="Animal_products",
        ),
    ]
