# Generated by Django 4.2.19 on 2025-03-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_remove_dish_animal_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="Animal_products",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="Dish_1",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="Dish_2",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="Dish_3",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="Dish_4",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="Dish_5",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="Dish_6",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="Dish_7",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="Dish_8",
        ),
        migrations.AddField(
            model_name="meal",
            name="Dishes",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
