# Generated by Django 4.2.19 on 2025-03-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_remove_meal_animal_products_remove_meal_dish_1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meal",
            old_name="Quantity",
            new_name="Food_Groups",
        ),
        migrations.AddField(
            model_name="meal",
            name="Quantities",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
