# Generated by Django 4.2.19 on 2025-03-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_rename_quantity_meal_food_groups_meal_quantities"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="Food_Groups_Counter",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
