# Generated by Django 4.2.19 on 2025-03-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_remove_meal_chicken_remove_meal_dairy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="Food_Groups_Quantities",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
