# Generated by Django 4.2.19 on 2025-03-07 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_dish_food_groups_quantities"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dish",
            old_name="Food_Groups_Quantities",
            new_name="Unique_Food_Groups_Quantities",
        ),
    ]
