# Generated by Django 4.2.19 on 2025-03-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app",
            "0017_rename_food_groups_quantities_dish_unique_food_groups_quantities",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="Chicken",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="Dairy",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="Fish",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="Fruit",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="Meat",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="Nuts_and_seeds",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="Plant_protein",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="Vegetables",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
