# Generated by Django 4.2.6 on 2025-03-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0018_meal_chicken_meal_dairy_meal_fish_meal_fruit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="npitem",
            name="checked",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="npitem",
            name="shopping_list",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
