# Generated by Django 4.2.19 on 2025-04-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0019_npitem_checked_npitem_shopping_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="Chicken",
        ),
        migrations.AddField(
            model_name="allcombos5",
            name="che_q",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="allcombos5",
            name="che_s",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="allcombos5",
            name="dai_q",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="allcombos5",
            name="dai_s",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="allcombos5",
            name="dis_s",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="allcombos5",
            name="fis_q",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="allcombos5",
            name="fru_q",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="allcombos5",
            name="fru_s",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="allcombos5",
            name="leg_q",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="allcombos5",
            name="leg_s",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="allcombos5",
            name="mea_q",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="allcombos5",
            name="mea_s",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="allcombos5",
            name="nns_q",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="allcombos5",
            name="nns_s",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="allcombos5",
            name="oil_q",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="allcombos5",
            name="oil_s",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="allcombos5",
            name="veg_q",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="allcombos5",
            name="veg_s",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
