# Generated by Django 4.2.19 on 2025-04-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0020_remove_meal_chicken_allcombos5_che_q_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="allcombos5",
            old_name="dis_s",
            new_name="fis_s",
        ),
        migrations.RenameField(
            model_name="allcombos5",
            old_name="oil_q",
            new_name="jui_q",
        ),
        migrations.RenameField(
            model_name="allcombos5",
            old_name="oil_s",
            new_name="jui_s",
        ),
        migrations.AddField(
            model_name="allcombos5",
            name="oif_q",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="allcombos5",
            name="oif_s",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="allcombos5",
            name="prm_q",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="allcombos5",
            name="prm_s",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
