# Generated by Django 4.2.19 on 2025-04-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0021_rename_dis_s_allcombos5_fis_s_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allcombos5",
            name="che_q",
        ),
        migrations.RemoveField(
            model_name="allcombos5",
            name="che_s",
        ),
        migrations.RemoveField(
            model_name="allcombos5",
            name="dai_q",
        ),
        migrations.RemoveField(
            model_name="allcombos5",
            name="dai_s",
        ),
        migrations.RemoveField(
            model_name="allcombos5",
            name="fis_q",
        ),
        migrations.RemoveField(
            model_name="allcombos5",
            name="fis_s",
        ),
        migrations.RemoveField(
            model_name="allcombos5",
            name="fru_q",
        ),
        migrations.RemoveField(
            model_name="allcombos5",
            name="fru_s",
        ),
        migrations.RemoveField(
            model_name="allcombos5",
            name="jui_q",
        ),
        migrations.RemoveField(
            model_name="allcombos5",
            name="jui_s",
        ),
        migrations.RemoveField(
            model_name="allcombos5",
            name="leg_q",
        ),
        migrations.RemoveField(
            model_name="allcombos5",
            name="leg_s",
        ),
        migrations.RemoveField(
            model_name="allcombos5",
            name="mea_q",
        ),
        migrations.RemoveField(
            model_name="allcombos5",
            name="mea_s",
        ),
        migrations.RemoveField(
            model_name="allcombos5",
            name="nns_q",
        ),
        migrations.RemoveField(
            model_name="allcombos5",
            name="nns_s",
        ),
        migrations.RemoveField(
            model_name="allcombos5",
            name="oif_q",
        ),
        migrations.RemoveField(
            model_name="allcombos5",
            name="oif_s",
        ),
        migrations.RemoveField(
            model_name="allcombos5",
            name="prm_q",
        ),
        migrations.RemoveField(
            model_name="allcombos5",
            name="prm_s",
        ),
        migrations.RemoveField(
            model_name="allcombos5",
            name="veg_q",
        ),
        migrations.RemoveField(
            model_name="allcombos5",
            name="veg_s",
        ),
        migrations.AddField(
            model_name="meal",
            name="che_q",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="che_s",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="dai_q",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="dai_s",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="fis_q",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="fis_s",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="fru_q",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="fru_s",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="jui_q",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="jui_s",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="leg_q",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="leg_s",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="mea_q",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="mea_s",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="nns_q",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="nns_s",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="oif_q",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="oif_s",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="prm_q",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="prm_s",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="veg_q",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="veg_s",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
