# Generated by Django 4.2.6 on 2025-05-12 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0022_remove_allcombos5_che_q_remove_allcombos5_che_s_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meal",
            old_name="prm_q",
            new_name="blv_q",
        ),
        migrations.RenameField(
            model_name="meal",
            old_name="prm_s",
            new_name="blv_s",
        ),
    ]
