# Generated by Django 4.2.19 on 2025-06-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0023_rename_prm_q_meal_blv_q_rename_prm_s_meal_blv_s"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allcombos5",
            name="Meal_1",
        ),
        migrations.RemoveField(
            model_name="allcombos5",
            name="Meal_2",
        ),
        migrations.RemoveField(
            model_name="allcombos5",
            name="Meal_3",
        ),
        migrations.RemoveField(
            model_name="allcombos5",
            name="Meal_4",
        ),
        migrations.RemoveField(
            model_name="allcombos5",
            name="Meal_5",
        ),
        migrations.RemoveField(
            model_name="npitem",
            name="ratio",
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(fields=["Country"], name="app_meal_Country_0e7c7c_idx"),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(fields=["Type"], name="app_meal_Type_442237_idx"),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(fields=["Winter"], name="app_meal_Winter_1d8ac8_idx"),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(fields=["Spring"], name="app_meal_Spring_968dd3_idx"),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(fields=["Summer"], name="app_meal_Summer_fe9e25_idx"),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(fields=["Autumn"], name="app_meal_Autumn_485e7b_idx"),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(fields=["Meat"], name="app_meal_Meat_b70b36_idx"),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(fields=["Dairy"], name="app_meal_Dairy_ddb72e_idx"),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["Nuts_and_seeds"], name="app_meal_Nuts_an_70b132_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(fields=["Fish"], name="app_meal_Fish_9611b0_idx"),
        ),
        migrations.DeleteModel(
            name="AllCombos5",
        ),
    ]
