# Generated by Django 4.2.19 on 2025-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0026_userachievements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userachievements",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
