# Generated by Django 4.2.19 on 2025-06-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0027_alter_userachievements_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userachievements",
            name="level",
            field=models.IntegerField(default=1),
        ),
    ]
