# Generated by Django 4.2.19 on 2025-06-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0029_userachievementscalculation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userachievementscalculation",
            name="day",
            field=models.CharField(default="", max_length=255),
        ),
    ]
