# Generated by Django 4.2.19 on 2025-06-10 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0030_alter_userachievementscalculation_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userachievementscalculation",
            name="points",
        ),
    ]
